---

    - name: db | create database service user
      become_user: postgres
      postgresql_user:
        name: "{{ service_db_user }}"
        password: "{{ service_db_password }}"

    - name: db | create service database
      become_user: postgres
      postgresql_db:
        name: "{{ service_db_name }}"
        encoding: UTF-8
        lc_collate: en_US.utf8
        lc_ctype: en_US.utf8
        template: template0
        owner: "{{ service_db_user }}"

