---

    - name: cleanup log | copy script to delete old log files
      template:
        src: cronjob_cleanup_log.sh.j2
        dest: "{{ db_bin_dir }}/cleanup_log.sh"
        owner: postgres
        group: postgres
        #group: www-data
        mode: 0774
      tags:
          - copy_script

    - name: cleanup log | set cleanup cronjob run daily
      cron:
        name: cleanup logs older than {{ db_log_retention_in_days }}
        user: postgres
        special_time: daily
        state: present
        job: "{{ db_bin_dir }}/cleanup_log.sh 2>&1 | logger -t '[log cleanup]'"


