---

    - name: install nginx
      apt:
        name: nginx
        state: present

    - name: compose the cert filename
      set_fact:
          cert_partial_filename: "{{ (ec2_tag_cluster == 'prod') | ternary('', 'all_') }}{{ cert_dns }}_{{ org_public_domain | replace('.', '_') }}"

    - name: copy ssl cert dir to service host
      copy:
        src: "{{ local_certs_dir }}/{{ cert_dns }}/{{ cert_partial_filename }}_bundle.crt"
        dest: "{{ nginx_ssl_dest_dir }}/{{ cert_partial_filename }}_bundle.crt"
        mode: 0644
      when: enable_ssl

    - name: copy ssl private_key to service host
      copy:
        src: "{{ local_certs_dir }}/{{ cert_dns }}/{{ cert_partial_filename }}.key"
        dest: "{{ nginx_ssl_dest_dir }}/{{ cert_partial_filename }}.key"
        mode: 0600
      when: enable_ssl

    # create sites-available
    # with_ssl is internal to the template; enable_ssl defines if (web) service will use https
    - include_tasks: drop_nginx_config.yml
      vars:
          with_ssl: True
      when: enable_ssl

    - include_tasks: drop_nginx_config.yml
      vars:
          with_ssl: False

    # disabled default site
    - name: ensure default site is disabled
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: link ssl CERT to correct file
      file:
        src: "{{ nginx_ssl_dest_dir }}/{{ cert_partial_filename }}_bundle.crt"
        dest: "{{ nginx_ssl_dest_dir }}/{{ cert_dns }}.crt"
        state: link
      when: enable_ssl
      notify: reload nginx


    - name: link ssl KEY to correct file
      file:
        src: "{{ nginx_ssl_dest_dir }}/{{ cert_partial_filename }}.key"
        dest: "{{ nginx_ssl_dest_dir }}/{{ cert_dns }}.key"
        state: link
      when: enable_ssl
      notify: reload nginx


    - name: ensure {{ service_name }} site is enabled
      file:
        src: /etc/nginx/sites-available/{{ enable_ssl | ternary('ssl', 'nonssl') }}_{{ service_name }}
        dest: /etc/nginx/sites-enabled/{{ service_name }}
        state: link
      notify: reload nginx


    - name: restart nginx
      service:
          name: nginx
          state: restarted

