# assumes it's running inside loop over nginx_servers
---

    #- name: compose the cert filename
    #  set_fact:
    #    cert_partial_filename: "{{ (ec2_tag_cluster in ['prod', 'vagrant']) | ternary('', 'all_') }}{{ service_cert_name }}_{{ org_public_domain | replace('.', '_') }}"
    #  when: cert_partial_filename is not defined

    - name: compose the cert filename, when devo
      set_fact:
        cert_partial_filename: "all_{{ service_cert_name }}_{{ org_public_domain | replace('.', '_') }}"
      when: ec2_tag_cluster not in ['prod', 'vagrant'] and server.hx_subdomain is defined and server.hx_subdomain != ''

    - name: compose the cert filename, when prod
      set_fact:
        cert_partial_filename: "{{ service_cert_name }}_{{ org_public_domain | replace('.', '_') }}"
      when: ec2_tag_cluster in ['prod', 'vagrant'] and (server.hx_subdomain is not defined or server.hx_subdomain == '')

    - name: generate CSR and PRIVATE keys in service host with hx_subdomain
      command:
        cmd: >
          openssl req -newkey rsa:2048 -nodes
           -keyout {{ target_certs_dir }}/{{ cert_partial_filename }}.key
           -out {{ target_certs_dir }}/{{ cert_partial_filename }}.csr
           -subj "/C=US/ST=Massachusetts/O=HX/OU=Headquarter/CN={{ server.hx_subdomain }}.{{ webserver_dns }}"
        creates: "{{ target_certs_dir }}/{{ cert_partial_filename }}.csr"
      when: not is_harvard_domain and (server.hx_subdomain is defined and server.hx_subdomain != '')

    - name: generate CSR and PRIVATE keys in service host WITHOUT hx_subdomain
      command:
        cmd: >
          openssl req -newkey rsa:2048 -nodes
           -keyout {{ target_certs_dir }}/{{ cert_partial_filename }}.key
           -out {{ target_certs_dir }}/{{ cert_partial_filename }}.csr
           -subj "/C=US/ST=Massachusetts/O=HX/OU=Headquarter/CN={{ server.hx_subdomain }}.{{ webserver_dns }}"
        creates: "{{ target_certs_dir }}/{{ cert_partial_filename }}.csr"
      when: not is_harvard_domain and (server.hx_subdomain is not defined or server.hx_subdomain == '')

    - name: copy ssl PRIVATE_key to service host
      copy:
        src: "{{ local_certs_dir }}/certs/{{ cert_partial_filename }}.key"
        dest: "{{ target_certs_dir }}/{{ cert_partial_filename }}.key"
        mode: 0600
      when: is_harvard_domain

    - name: generate ssl CERT to service host
      openssl_certificate:
        path: "{{ target_certs_dir }}/{{ cert_partial_filename }}_bundle.crt"
        privatekey_path: "{{ target_certs_dir }}/{{ cert_partial_filename }}.key"
        csr_path: "{{ target_certs_dir }}/{{ cert_partial_filename }}.csr"
        provider: selfsigned
        mode: 0644
      when: not is_harvard_domain

    - name: copy ssl CERT dir to service host
      copy:
        src: "{{ local_certs_dir }}/certs/{{ cert_partial_filename }}_bundle.crt"
        dest: "{{ target_certs_dir }}/{{ cert_partial_filename }}_bundle.crt"
        mode: 0644
      when: is_harvard_domain

    # TODO: this changes every renew? then overwrite
    - name: copy ssl INTERMEDIATE certs dir to service host
      copy:
        src: "{{ local_certs_dir }}/certs/{{ cert_partial_filename }}_interm.crt"
        dest: "{{ target_certs_dir }}/{{ cert_partial_filename }}_interm.crt"
        mode: 0640
      when: is_harvard_domain

    - name: generate diffie-hellman params 2048bits
      openssl_dhparam:
        path: "{{ target_certs_dir }}/dhparam.crt"
        state: present
        size: 2048
        force: no
        mode: 0640

    - name: link ssl CERT to correct file
      file:
        src: "{{ target_certs_dir }}/{{ cert_partial_filename }}_bundle.crt"
        dest: "{{ target_certs_dir }}/{{ service_cert_name }}.crt"
        state: link

    - name: link ssl KEY to correct file
      file:
        src: "{{ target_certs_dir }}/{{ cert_partial_filename }}.key"
        dest: "{{ target_certs_dir }}/{{ service_cert_name }}.key"
        state: link

    - name: link ssl INTERMEDIATE to correct file
      file:
        src: "{{ target_certs_dir }}/{{ cert_partial_filename }}_interm.crt"
        dest: "{{ target_certs_dir }}/{{ service_cert_name }}_interm.crt"
        state: link
      when: is_harvard_domain


