---

    - name: install nginx
      apt:
        name: nginx
        state: present

    - include_tasks: define_log_format.yml

    - include_tasks: config_connections_nofiles.yml

    - include_tasks: config_gzip.yml


    # disabled default site
    - name: ensure default site is disabled
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent


    # nginx need these when upstream doesn't respond
    - name: create crude 500 error page
      shell: echo "<html><body>500 server error</body></html>" > "{{ static_dir }}/50x.html"
      args:
        creates: "{{ static_dir }}/50x.html"

    - name: create crude 404 error page
      shell: echo "<html><body>404 not found</body></html>" > "{{ static_dir }}/404.html"
      args:
        creates: "{{ static_dir }}/404.html"


    - name: config server
      include_tasks: config_server.yml
      loop: '{{ nginx_servers }}'


    - name: restart nginx
      service:
          name: nginx
          state: restarted

