---

    - name: install nginx and pkg to webdav, auth
      apt:
        pkg:
          - 'nginx-full'
          - 'apache2-utils'
        state: present

    - include_tasks: define_log_format.yml

    - include_tasks: config_connections_nofiles.yml
      when: websockets is defined

    - include_tasks: config_gzip.yml


    # disabled default site
    - name: ensure default site is disabled
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent


    # nginx need these when upstream doesn't respond
    - name: create crude 500 error page
      shell: echo "<html><body>500 server error</body></html>" > "{{ static_dir }}/50x.html"
      args:
        creates: "{{ static_dir }}/50x.html"

    - name: create crude 404 error page
      shell: echo "<html><body>404 not found</body></html>" > "{{ static_dir }}/404.html"
      args:
        creates: "{{ static_dir }}/404.html"

    - name: create crude 503 service unavailable
      shell: echo "<html><body>503 service unavailable</body></html>" > "{{ static_dir }}/maintenance.html"

    - name: config server
      include_tasks: config_server.yml
      loop: '{{ nginx_servers }}'
      loop_control:
        loop_var: server


    - name: restart nginx
      service:
          name: nginx
          state: restarted

