---
    - name: create varnishlog pid dir
      file:
          path: /run/varnishlog
          owner: varnishlog
          group: varnish
          state: directory

    - name: create varnishncsa pid dir
      file:
          path: /run/varnishncsa
          owner: varnishlog
          group: varnish
          state: directory

    # from https://github.com/varnishcache/pkg-varnish-cache/issues/31
    - name: drop varnishlog.service
      copy:
          src: ../files/varnishlog.service
          dest: /lib/systemd/system/varnishlog.service
          owner: root
          group: root

    - name: drop varnishncsa.service
      copy:
        src: ../files/varnishncsa.service
        dest: /lib/systemd/system/varnishncsa.service
        owner: root
        group: root

    - name: stop varnishlog service
      systemd:
          name: varnishlog
          daemon_reload: yes
          state: stopped

    - name: start varnishlog service
      systemd:
          name: varnishlog
          enabled: yes
          daemon_reload: yes
          state: started

    - name: stop varnishncsa service
      systemd:
          name: varnishncsa
          daemon_reload: yes
          state: stopped

    - name: start varnishncsa service
      systemd:
          name: varnishncsa
          enabled: yes
          daemon_reload: yes
          state: started

