---

- import_playbook: common_play.yml


- hosts: '{{ target_hosts | default("tag_service_catchpy", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  vars_files:
    - vars/common_vars.yml
    - vars/catchpy_vars.yml
  handlers:
    - include_tasks: handlers/main.yml

  tasks:
    - name: install webapp
      include_role:
        name: webapp_install

    - name: run migration and collectstatic
      include_tasks: 'roles/webapp_install/tasks/django_manage.yml'

    - name: create django admin user
      include_tasks: 'roles/webapp_install/tasks/django_admin_user.yml'

    - name: config nginx
      include_role:
        name: nginx


# install log/metrics scripts, syslog to s3, put-metrics to cloudwatch
- import_playbook: cloudwatch_scripts_play.yml

- import_playbook: nginx_backup_play.yml



