---
#
# all playbooks must run this first:
# - update ubuntu packages
# - create hx devel users with sudo powers!
#


- hosts: '{{ target_hosts | default("all", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars:
    local_user:
      name: '{{ service_name }}'
      authorized: []
  vars_files:
      - vars/common_vars.yml
      - vars/{{ ec2_tag_service }}_vars.yml

  tasks:
      - name: check timesync
        shell: |
            timedatectl | grep 'System clock synchronized' | awk '{print $4}'
        register: timesync

      - name: stop timesync
        command: timedatectl set-ntp no
        when: timesync.stdout != 'yes' #and ec2_tag_cluster != 'vagrant'

      - name: add aws time server
        lineinfile:
          path: /etc/systemd/timesyncd.conf
          regexp: '^NTP='
          insertafter: '^#NTP='
          line: "{{ (ec2_tag_cluster != 'vagrant') | ternary('NTP=169.254.169.123', 'NTP=us.pool.ntp.org') }}"
        when: timesync.stdout != 'yes'

      - name: restart timesync
        systemd:
          name: systemd-timesyncd
          state: restarted
          enabled: yes
        when: timesync.stdout != 'yes' #and ec2_tag_cluster != 'vagrant'

      - include_role:
          name: external/jmcvetta.passwordless_sudo

      - include_role:
          name: external/nmaekawa.apt
        # - install acl pkg for become_user; see:
        #   https://stackoverflow.com/questions/46352173/ansible-failed-to-set-permissions-on-the-temporary
        # - install jq pkg to identify extra ebs mountpoint
        vars:
          apt_other_packages: '{{ ["acl", "jq"] + apt_service_packages }}'

      # unattended-updates is installed by default by nmaekawa.apt but not properly
      # configured... see:
      # - https://haydenjames.io/how-to-enable-unattended-upgrades-on-ubuntu-debian/
      # - http://disq.us/p/2c5x17d     (comment)
      - name: unattended-updates to clean apt cache every 7 days
        lineinfile:
          path: /etc/apt/apt.conf.d/20auto-upgrades
          regexp: 'AutocleanInterval'
          line: 'APT::Periodic::AutocleanInterval "7";'
        when: ec2_tag_cluster != 'vagrant'

      - name: unattended-updates to remove unused dependencies
        lineinfile:
          path: /etc/apt/apt.conf.d/50unattended-upgrades
          regexp: 'Remove-Unused-Dependencies'
          line: 'Unattendet-Upgrade::Remov1e-Unused-Dependencies "true";'
        when: ec2_tag_cluster != 'vagrant'

      - include_role:
          name: external/Stouts.users
        vars:
          users_users: '{{ users_developers + [local_user] }}'

      - include_role:
          name: external/nmaekawa.extra-ebs
        when: use_aws

