---
#
# all playbooks must run this first:
# - update ubuntu packages
# - create hx devel users with sudo powers!
#


- hosts: '{{ target_hosts | default("all", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  gather_facts: False
  vars_files:
      - vars/common_vars.yml

  tasks:
      # https://stackoverflow.com/a/54143390
      - name: link to python3
        raw: |
          if [ -f /usr/bin/python3 ] && [ ! -f /usr/bin/python ]; then
            ln --symbolic /usr/bin/python3 /usr/bin/python
          fi
        when: ansible_version.full < "2.8.0"


      - include_role:
          name: external/jmcvetta.passwordless_sudo

      - include_role:
          name: external/nmaekawa.apt

      - include_role:
          name: external/Stouts.users
        vars:
          users_users: '{{ users_developers }}'
