---
#
# all playbooks must run this first:
# - update ubuntu packages
# - create hx devel users with sudo powers!
#


- hosts: '{{ target_hosts | default("all", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  gather_facts: False
  vars_files:
      - vars/common_vars.yml

  tasks:
      # https://stackoverflow.com/a/54143390
      - name: link to python3
        raw: |
          if [ -f /usr/bin/python3 ] && [ ! -f /usr/bin/python ]; then
            ln --symbolic /usr/bin/python3 /usr/bin/python
          fi
        when: ansible_version.full < "2.8.0"


      - name: stop timesync
        command: timedatectl set-ntp no
        when: timesync.stdout != 'yes'

      - name: add aws time server
        lineinfile:
          path: /etc/systemd/timesyncd.conf
          regexp: '^NTP='
          insertafter: '^#NTP='
          line: 'NTP=169.254.169.123'
        when: timesync.stdout != 'yes'

      - name: restart timesync
        systemd:
          name: systemd-timesyncd
          state: restarted
          enabled: yes
        when: timesync.stdout != 'yes'


      - include_role:
          name: external/jmcvetta.passwordless_sudo

      - include_role:
          name: external/nmaekawa.apt

      - include_role:
          name: external/Stouts.users
        vars:
          users_users: '{{ users_developers }}'
