---
#
# all playbooks must run this first:
# - update ubuntu packages
# - create hx devel users with sudo powers!
#


- hosts: '{{ target_hosts | default("all", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  gather_facts: False
  vars_files:
      - vars/common_vars.yml

  tasks:
      # https://stackoverflow.com/a/54143390
      - name: link to python3
        raw: |
          if [ -f /usr/bin/python3 ] && [ ! -f /usr/bin/python ]; then
            ln --symbolic /usr/bin/python3 /usr/bin/python
          fi
        when: ansible_version.full < "2.8.0"


      - name: check timesync
        shell: |
            timedatectl | grep 'System clock synchronized' | awk '{print $4}'
        register: timesync

      - name: stop timesync
        command: timedatectl set-ntp no
        when: timesync.stdout != 'yes' #and ec2_tag_cluster != 'vagrant'

      - name: add aws time server
        lineinfile:
          path: /etc/systemd/timesyncd.conf
          regexp: '^NTP='
          insertafter: '^#NTP='
          line: "{{ (ec2_tag_cluster != 'vagrant') | ternary('NTP=169.254.169.123', 'NTP=us.pool.ntp.org') }}"
        when: timesync.stdout != 'yes'

      - name: restart timesync
        systemd:
          name: systemd-timesyncd
          state: restarted
          enabled: yes
        when: timesync.stdout != 'yes' #and ec2_tag_cluster != 'vagrant'


      - include_role:
          name: external/jmcvetta.passwordless_sudo

      - include_role:
          name: external/nmaekawa.apt
        # install acl pkg for become_user; see:
        # https://stackoverflow.com/questions/46352173/ansible-failed-to-set-permissions-on-the-temporary
        vars:
          apt_other_packages: ["acl"]

      # unattended-updates is installed by default by nmaekawa.apt but not properly
      # configured... see:
      # - https://haydenjames.io/how-to-enable-unattended-upgrades-on-ubuntu-debian/
      # - http://disq.us/p/2c5x17d     (comment)
      - name: unattended-updates to clean apt cache every 7 days
        lineinfile:
          path: /etc/apt/apt.conf.d/20auto-upgrades
          regexp: 'AutocleanInterval'
          line: 'APT::Periodic::AutocleanInterval "7";'

      - name: unattended-updates to remove unused dependencies
        lineinfile:
          path: /etc/apt/apt.conf.d/50unattended-upgrades
          regexp: 'Remove-Unused-Dependencies'
          line: 'Unattendet-Upgrade::Remove-Unused-Dependencies "true";'

      - include_role:
          name: external/Stouts.users
        vars:
          users_users: '{{ users_developers }}'
