---
#
# assumes common_play.yml already applied to all involved inventory
#

- import_playbook: common_play.yml

- hosts: '{{ target_hosts | default("tag_service_hxat", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars:
    local_user:
      name: '{{ service_name }}'
      authorized: []
  vars_files:
    - vars/common_vars.yml
    - vars/hxat_vars.yml

  tasks:
    - include_role:
        name: external/nmaekawa.apt
      vars:
        apt_other_packages: "{{ apt_required_packages_hxat }}"

    - include_role:
        name: external/Stouts.users
      vars:
        users_users: '{{ [local_user] }}'

    - include_role:
        name: external/nmaekawa.extra-ebs
      when: use_aws

    - name: install redis
      include_role:
        name: external/geerlingguy.redis


- hosts: '{{ target_hosts | default("tag_service_hxat", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  vars_files:
    - vars/common_vars.yml
    - vars/hxat_vars.yml
  handlers:
    - include_tasks: handlers/main.yml

  tasks:
    - name: install webapp
      include_role:
        name: webapp_install
      vars:
        wsgi_module: 'annotationsx'  # when wsgi module doesn't share same name as service_name

    - name: run migration and collectstatic
      include_tasks: 'roles/webapp_install/tasks/django_manage.yml'
      environment:
        HXAT_DOTENV_PATH': '{{ service_dotenv_path }}'

    - name: create django admin user
      include_tasks: 'roles/webapp_install/tasks/django_admin_user.yml'

    - name: config nginx
      include_role:
        name: nginx
      vars:
        #nginx_non_ssl_port: 5050
        #nginx_ssl_port: 5450
        nginx_template_path: roles/nginx/templates/nginx_hxmirador.j2




