---

#- import_playbook: common_play.yml


- hosts: '{{ target_hosts | default("tag_service_hxat", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  vars_files:
    - vars/common_vars.yml
    - vars/hxat_vars.yml
  handlers:
    - include_tasks: handlers/main.yml

  tasks:
    #- name: install redis
    #  include_role:
    #    name: external/geerlingguy.redis

    - name: install webapp
      include_role:
        name: webapp_install

    - name: run migration and collectstatic
      include_tasks: 'roles/webapp_install/tasks/django_manage.yml'

    - name: create django admin user
      include_tasks: 'roles/webapp_install/tasks/django_admin_user.yml'

    - name: config nginx
      include_role:
        name: nginx

    - name: cronjob to clear sessions
      cron:
        name: 'clear django sessions'
        user: '{{ service_user }}'
        hour: '7'
        minute: '0'
        state: present
        job: >
          {{ service_name | upper }}_DOTENV_PATH={{ service_dotenv_path }} {{ service_venv_dir }}/bin/python3 {{ service_install_dir }}/manage.py clearsessions 2>&1 | logger -t '[clear django sessions]'


#- import_playbook: rds_service_dbdump_play.yml
#  vars:
#    project_name: hxat
#  when: ec2_tag_cluster == 'prod'
#
#- import_playbook: backup_play.yml





