---
- hosts: '{{ target_hosts | default("tag_mirador", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  gather_facts: False
  vars_files:
      - vars/common_vars.yml
      - vars/hxmirador_vars.yml

  tasks:
      - name: install python2
        raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
        register: result
        changed_when: "result.stdout != ''"


- hosts: '{{ target_hosts | default("tag_mirador", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars:
      local_user:
          name: '{{ service_name }}'
          authorized: []
  vars_files:
      - vars/common_vars.yml
      - vars/hxmirador_vars.yml

  roles:
      - external/jmcvetta.passwordless_sudo
      - { role: external/nmaekawa.apt, apt_other_packages: "{{ apt_required_packages_hxmirador }}" }
      - external/Stouts.users
      - { role: external/Stouts.users, users_users: '{{ users_developers + [local_user] }}' }


- hosts: '{{ target_hosts | default("tag_mirador", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  vars_files:
      - vars/common_vars.yml
      - vars/hxmirador_vars.yml
  handlers:
    - include_tasks: handlers/main.yml

  tasks:
      - name: setup webserver name
        include_tasks: 'roles/facts_setup/tasks/webserver_dns.yml'

      - name: install webapp
        include_role:
            name: webapp_install

      - name: run migration and collectstatic
        include_tasks: 'roles/webapp_install/tasks/django_manage.yml'

      - name: create django admin user
        include_tasks: 'roles/webapp_install/tasks/django_admin_user.yml'

      - name: config nginx
        include_role:
            name: nginx
        vars:
            #nginx_non_ssl_port: 5050
            #nginx_ssl_port: 5450
            nginx_template_path: roles/nginx/templates/nginx_hxmirador.j2


- hosts: '{{ target_hosts | default("tag_mirador", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  vars_files:
      - vars/common_vars.yml
      - vars/hxmirador_vars.yml
  handlers:
    - include_tasks: handlers/main.yml

  tasks:
      - name: install redis
        include_role:
            name: external/geerlingguy.redis



