#
# ATT: only apply this when in a VAGRANT cluster
####################################################################
#
# assumes common_play.yml already applied to all involved inventory
#

- hosts: '{{ target_hosts | default("tag_service_mockids", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars:
      local_user:
          name: '{{ service_name }}'
          authorized: []
  vars_files:
      - vars/common_vars.yml
      - vars/loris_vars.yml

  tasks:
      - include_role:
          name: external/nmaekawa.apt
        vars:
          apt_other_packages: "{{ apt_required_packages_loris }}"

      - include_role:
          name: external/Stouts.users
        vars:
          users_users: '{{ [local_user] }}'



- hosts: '{{ target_hosts | default("tag_service_mockids", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars_files:
      - vars/common_vars.yml
      - vars/loris_vars.yml
  vars:
    loris_git_repo: 'https://github.com/loris-imageserver/loris.git'
    loris_git_version: 'v2.3.3'

  handlers:
    - include: handlers/main.yml

  tasks:
      - name: setup ids loris
        include_role:
            name: hx.loris
        vars:
            vagrant_webserver_dns: 'ids.vm'
            local_image_sample_path_tar_gz: '/Volumes/Projects/Dev_Team/images/ids_images_sample.tar.gz'
            hx_host: '{{ ec2_private_ip_address }}'

      - name: setup proxy
        include_role:
            name: nginx
        vars:
          vagrant_webserver_dns: 'ids.vm'
          nginx_servers:
            - nginx_template_path: roles/nginx/templates/nginx_ids.j2
              cfg_filename: '{{ service_name }}_proxy'
              nginx_nonssl_port: 80
              nginx_ssl_port: 443
              locations:
                - name: 'ids_proxy'
                  prefix: '/'
                  root: '{{ service_static_dir }}'
                  getonly: 'yes'
                  add_rewrites: 'yes'
                  gunicorn_timeout_seconds: '{{ gunicorn_timeout_seconds }}'
                  service_gunicorn_host: '{{ hostvars[inventory_hostname].ec2_private_ip_address }}'
                  service_gunicorn_port: '{{ service_gunicorn_port }}'






