---
#
# assumes common_play.yml already applied to all involved inventory
#

- hosts: '{{ target_hosts | default("tag_service_reverseproxy", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars_files:
      - vars/common_vars.yml
      - vars/loris_vars.yml

  handlers:
    - include: handlers/main.yml

  tasks:
    - name: ensure static_dir exists
      file:
        path: '{{ service_static_dir }}'
        state: directory
        owner: root
        group: www-data

    - name: setup proxy
      include_role:
          name: nginx
      vars:
        nginx_servers:
          - nginx_template_path: roles/nginx/templates/nginx_loris.j2
            service_server_name: '{{ service_name }}'
            nginx_nonssl_port: 80
            nginx_ssl_port: 443
            static_dir: '{{ service_static_dir }}'

  # install log/metrics scripts, syslog to s3, put-metrics to cloudwatch
- import_playbook: cloudwatch_scripts_play.yml
  when: ec2_tag_cluster == 'prod'

- import_playbook: nginx_backup_play.yml
  when: ec2_tag_cluster == 'prod'

- import_playbook: route53_play.yml
  when: "ec2_tag_cluster not in ['prod', 'demo', 'vagrant']"




