---
#
# assumes common_play.yml already applied to all involved inventory
#

- hosts: '{{ target_hosts | default("tag_service_reverseproxy", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars_files:
      - vars/common_vars.yml
      - vars/loris_dedicated_varnish_vars.yml
  vars:
    loris_git_repo: 'https://github.com/loris-imageserver/loris.git'
    loris_git_version: 'v2.2.0'

  handlers:
    - include: handlers/main.yml

  tasks:
      - name: setup proxy
        include_role:
            name: nginx
        vars:
            static_dir: '{{ service_static_dir }}'
            nginx_template_path: roles/nginx/templates/nginx_loris.j2


- hosts: '{{ target_hosts | default("all", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars:
      project_name: '{{ hostvars[inventory_hostname].ec2_tag_project | mandatory}}'
      service_role: '{{ hostvars[inventory_hostname].ec2_tag_service | mandatory}}'
      cluster_env: '{{ (hostvars[inventory_hostname].ec2_tag_cluster == "prod")| ternary("prod", "devo") }}'
      cronjob_scripts_dir: '/usr/local/bin'
      cloudwatch_namespace: '{{ cloudwatch_namespace_prefix }}/{{ project_name }}'
  vars_files:
      - vars/common_vars.yml
      - vars/loris_dedicated_varnish_vars.yml

  tasks:

      - debug:
          msg: "project_name={{ project_name }}; service_role={{ service_role }}; cluster_env={{ cluster_env }}; namespace={{ cloudwatch_namespace }}"

      #
      # 19nov18 naomi: skipping since this is done via cloudformation
      # -------------------------------------------------------------
      # associate proper instance profile for permissions
      #- import_tasks: roles/external/nmaekawa.iam-instance-profile/tasks/associate_iam_instance_profile.yml
      #  vars:
      #      instance_profile_name: "hx_{{ project_name }}-{{ cluster_env }}_instance_profile"
      #      instance_id_to_associate: '{{ hostvars[inventory_hostname].ec2_id }}'
      #  when: "use_aws"

      - import_role:
          name: external/Stouts.users
        vars:
            users_enabled: yes
            users_users:
                - name: cloudwatch
                  authorized: []
            users_to_install:
                - cloudwatch
        when: "use_aws"

      - import_role:
          name: external/nmaekawa.cloudwatch
        vars:
            script_install_dir: '{{ cronjob_scripts_dir }}'
            cronjob_owner: cloudwatch
        when: "use_aws"

      # install script for syslog backup
      - import_tasks: roles/external/nmaekawa.cloudwatch/tasks/install_s3_backup.yml
        vars:
            script_install_dir: '{{ cronjob_scripts_dir }}'
            cronjob_owner: root
            s3_backup_prefix: '{{ cluster_env }}/{{ project_name }}'
            file_backup_prefix: '{{ service_role }}_{{ ansible_ec2_instance_id }}'
            files_to_backup:
                - /var/log/syslog.1
        when: "use_aws"

      # install script for nginx logs backup
      - import_tasks: roles/external/nmaekawa.cloudwatch/tasks/install_s3_backup.yml
        vars:
            script_install_dir: '{{ cronjob_scripts_dir }}'
            cronjob_owner: root
            s3_backup_prefix: '{{ cluster_env }}/{{ project_name }}'
            file_backup_prefix: '{{ service_role }}_{{ ansible_ec2_instance_id }}'
            files_to_backup:
                - /var/log/nginx/access.log.1
                - /var/log/nginx/error.log.1
        when: "use_aws"



