---
- hosts: all
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  gather_facts: False
  vars_files:
      - vars/loris_vars.yml

  tasks:
  - name: install python2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)


- hosts: tag_loris
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars_files:
      - vars/loris_vars.yml

  roles:
      - external/jmcvetta.passwordless_sudo
      - { role: external/nmaekawa.apt, apt_other_packages: "{{ apt_required_packages_loris }}" }
      - external/Stouts.users


- hosts: tag_loris
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars_files:
      - vars/loris_vars.yml
  vars:
    loris_git_repo: 'https://github.com/loris-imageserver/loris.git'
    loris_git_version: 'v2.2.0'

  handlers:
    - include: handlers/main.yml

  tasks:
      - name: set webserver_dns
        set_fact:
            webserver_dns: "{{ ec2_public_dns_name | default('loris.vm') }}"

      - name: create loris dirs
        file:
            path: '{{ item }}'
            owner: '{{ loris_user }}'
            group: '{{ loris_user }}'
            state: directory
        with_items: '{{ loris_dirs }}'

  #      - import_role:
  #        name: external/atg.loris
  #
      - include_tasks: roles/hx.loris/tasks/python_dependencies.yml
      - include_tasks: roles/hx.loris/tasks/install_loris.yml
      - include_tasks: roles/hx.loris/tasks/config_loris.yml
      - include_tasks: roles/hx.loris/tasks/config_nginx.yml

      - include_tasks: roles/hx.loris/tasks/aws_creds.yml
        when: tag_cluster == 'vagrant' and ( loris_s3_bucket_prefix is defined )

      - include_tasks: roles/hx.loris/tasks/setup_gunicorn.yml

