---
- hosts: '{{ target_hosts | default("all", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  gather_facts: False
  vars_files:
      - vars/common_vars.yml
      - vars/loris_dedicated_varnish_vars.yml

  tasks:
      - debug:
          msg: "hx_image_host is ({{ hx_image_host }})"

      - name: install python2
        raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
        register: result
        changed_when: "result.stdout != ''"


- hosts: '{{ target_hosts | default("all", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars:
      local_user:
          name: '{{ service_name }}'
          authorized: []
  vars_files:
      - vars/common_vars.yml
      - vars/loris_dedicated_varnish_vars.yml

  roles:
      - external/jmcvetta.passwordless_sudo
      - { role: external/nmaekawa.apt }
      - { role: external/Stouts.users, users_users: '{{ users_developers + [local_user] }}' }


- hosts: '{{ target_hosts | default("tag_service_loris", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars_files:
      - vars/common_vars.yml
      - vars/loris_dedicated_varnish_vars.yml
  vars:
    loris_git_repo: 'https://github.com/loris-imageserver/loris.git'
    loris_git_version: 'v2.2.0'

  handlers:
    - include: handlers/main.yml

  tasks:
      - include_role:
          name: external/nmaekawa.apt
        vars:
            apt_other_packages: '{{ apt_required_packages_loris }}'

      - name: setup loris
        include_role:
            name: hx.loris
        vars:
            local_image_sample_path_tar_gz: '/Volumes/Projects/Dev_Team/images/images_prod_20180824.tar.gz'


- hosts: '{{ target_hosts | default("all", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars:
      is_varnish: '{{ hostvars[inventory_hostname].ec2_tag_service | regex_search("varnish") }}'
      varnish_default_vcl_template_path: 'roles/varnishlog/templates/default_dedicated.vcl.j2'
      varnish_be: "{% if hostvars[inventory_hostname].ec2_tag_service == 'idsvarnish' %}\
                        {{ varnish_instances.ids.backend }}\
                   {% elif hostvars[inventory_hostname].ec2_tag_service == 'hxvarnish' %}\
                            {{ varnish_instances.hx.backend }}\
                   {% endif %}"
      varnish_listen_port: "{% if hostvars[inventory_hostname].ec2_tag_service == 'idsvarnish' %}\
                        {{ varnish_instances.ids.frontend.port }}\
                   {% elif hostvars[inventory_hostname].ec2_tag_service == 'hxvarnish' %}\
                        {{ varnish_instances.hx.frontend.port }}\
                   {% endif %}"
  vars_files:
      - vars/common_vars.yml
      - vars/loris_dedicated_varnish_vars.yml

  tasks:
      - name: install varnish
        include_role:
            name: external/geerlingguy.varnish
        when: is_varnish is defined and is_varnish == 'varnish'

      - name: enable varnishlog
        include_role:
            name: varnishlog
        when: is_varnish is defined and is_varnish == 'varnish'


- hosts: '{{ target_hosts | default("tag_service_reverseproxy", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars_files:
      - vars/common_vars.yml
      - vars/loris_dedicated_varnish_vars.yml
  vars:
    loris_git_repo: 'https://github.com/loris-imageserver/loris.git'
    loris_git_version: 'v2.2.0'

  handlers:
    - include: handlers/main.yml

  tasks:
      - name: setup proxy
        include_role:
            name: nginx
        vars:
            static_dir: '{{ service_static_dir }}'
            nginx_template_path: roles/nginx/templates/nginx_loris.j2


- hosts: '{{ target_hosts | default("all", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars:
      project_name: '{{ hostvars[inventory_hostname].ec2_tag_project | mandatory}}'
      service_name: '{{ hostvars[inventory_hostname].ec2_tag_service | mandatory}}'
      cluster: '{{ hostvars[inventory_hostname].ec2_tag_cluster | mandatory}}'
      cronjob_scripts_dir: '/usr/local/bin'
      cloudwatch_namespace: 'HX/CustomMetrics/{{ project_name }}'
      is_varnish: '{{ service_name | regex_search("varnish") }}'
  vars_files:
      - vars/common_vars.yml

  tasks:

      - debug:
          msg: "project_name={{ project_name }}; service_name={{ service_name }}; cluster={{ cluster }}; namespace={{ cloudwatch_namespace }}"

      # associate proper instance profile for permissions
      - import_tasks: roles/external/nmaekawa.iam.instance-profile/tasks/associate_iam_instance_profile.yml
        vars:
            instance_profile_name: "hx_{{ project_name }}-{{ cluster }}_instance_profile"
            instance_id_to_associate: '{{ hostvars[inventory_hostname].ec2_id }}'
        when: "use_aws"

      - import_role:
          name: external/Stouts.users
        vars:
            users_enabled: yes
            users_users:
                - name: cloudwatch
                  authorized: []
            users_to_install:
                - cloudwatch
        when: "use_aws"

      - import_role:
          name: external/nmaekawa.cloudwatch
        vars:
            script_install_dir: '{{ cronjob_scripts_dir }}'
            cronjob_owner: cloudwatch
        when: "use_aws"

      # install script for syslog backup
      - import_tasks: roles/external/nmaekawa.cloudwatch/tasks/install_s3_backup.yml
        vars:
            script_install_dir: '{{ cronjob_scripts_dir }}'
            cronjob_owner: root
            s3_backup_bucket_name: 'backups-hx-edu'
            s3_backup_prefix: '{{ cluster }}/{{ project_name }}'
            file_backup_prefix: '{{ service_name }}'
            files_to_backup:
                - /var/log/syslog.1
        when: "use_aws"

      # install script for nginx logs backup
      - import_tasks: roles/external/nmaekawa.cloudwatch/tasks/install_s3_backup.yml
        vars:
            script_install_dir: '{{ cronjob_scripts_dir }}'
            cronjob_owner: root
            s3_backup_bucket_name: 'backups-hx-edu'
            s3_backup_prefix: '{{ cluster }}/{{ project_name }}'
            file_backup_prefix: '{{ service_name }}'
            files_to_backup:
                - /var/log/nginx/access.log.1
                - /var/log/nginx/error.log.1
        when: "use_aws and service_name == 'reverseproxy'"

      # install script for varnish logs backup
      - import_tasks: roles/external/nmaekawa.cloudwatch/tasks/install_s3_backup.yml
        vars:
            script_install_dir: '{{ cronjob_scripts_dir }}'
            cronjob_owner: root
            s3_backup_bucket_name: 'backups-hx-edu'
            s3_backup_prefix: '{{ cluster }}/{{ project_name }}'
            file_backup_prefix: '{{ service_name }}'
            files_to_backup:
                - /var/log/varnish/varnishncsa.log
        when: "use_aws and is_varnish is defined and is_varnish == 'varnish'"


      # install script for images sync, if images instance
      - import_tasks: roles/external/nmaekawa.cloudwatch/tasks/install_s3_sync.yml
        vars:
            script_install_dir: '{{ cronjob_scripts_dir }}'
            cronjob_owner: "{{ service_name }}"
            s3_sync_bucket_name: 'sources-hx-edu'
            s3_sync_prefix: 'images'
            target_s3_sync_dir: '/opt/loris/data/images'
        when: "use_aws and service_name == 'loris'"

      - name: run initial s3 sync for images
        shell: >
            /usr/bin/aws s3 sync
            "s3://sources-hx-edu/images"
            "/opt/loris/data/images"
            2>&1 | logger -t "[s3 sync INITIAL]"
        when: "use_aws and service_name == 'loris'"




