---
- hosts: '{{ target_hosts | default("tag_loris", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  gather_facts: False
  vars_files:
      - vars/common_vars.yml

  tasks:
      - name: install python2
        raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
        register: result
        changed_when: "result.stdout != ''"


- hosts: '{{ target_hosts | default("tag_loris", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars:
      local_user:
          name: '{{ service_name }}'
          authorized: []
  vars_files:
      - vars/common_vars.yml
      - vars/loris_vars.yml

  roles:
      - external/jmcvetta.passwordless_sudo
      - { role: external/nmaekawa.apt, apt_other_packages: "{{ apt_required_packages_loris }}" }
      - { role: external/Stouts.users, users_users: '{{ users_developers + [local_user] }}' }


- hosts: '{{ target_hosts | default("tag_loris", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars_files:
      - vars/common_vars.yml
      - vars/loris_vars.yml
  vars:
    loris_git_repo: 'https://github.com/loris-imageserver/loris.git'
    loris_git_version: 'v2.2.0'

  handlers:
    - include: handlers/main.yml

  tasks:
      - name: setup facts
        include_role:
            name: facts_setup

      - name: setup loris
        include_role:
            name: hx.loris


- hosts: '{{ target_hosts | default("tag_loris", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars_files:
      - vars/common_vars.yml
      - vars/loris_vars.yml

  tasks:
      - name: install varnish
        include_role:
            name: external/geerlingguy.varnish

      - name: enable varnishlog
        include_role:
            name: varnishlog

#
# to set up the manifest server as a static nginx in
# the same instance as the proxy (and loris) do
# include_static_manifest: 'true'
#
- hosts: '{{ target_hosts | default("tag_loris", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars:
      include_static_manifest: 'false'
      local_manifests_path_tar_gz: '/Volumes/hx-images/manifests_dev_jpg.tar.gz'
  vars_files:
      - vars/common_vars.yml
      - vars/loris_vars.yml

  tasks:
      - name: setup proxy
        include_role:
            name: nginx
        vars:
            static_dir: '{{ service_static_dir }}'
            nginx_template_path: roles/nginx/templates/nginx_reverse_proxy.j2

      - name: transfer sample manifests tar.gz
        copy:
            src: '{{ local_manifests_path_tar_gz }}'
            dest: '/tmp'
            owner: 'www-data'
            group: 'www-data'
        when: (include_static_manifest is defined and include_static_manifest == 'true')

      - name: unarchive sample manifests tar.gz
        unarchive:
            src: '/tmp/{{ local_manifests_path_tar_gz | basename }}'
            dest: '{{ service_static_dir }}'
            owner: 'www-data'
            group: 'www-data'
            remote_src: yes
        when: (include_static_manifest is defined and include_static_manifest == 'true')



