---

- hosts: '{{ target_hosts | default("tag_service_postgres", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  become_user: root
  vars_files:
      - vars/common_vars.yml
      - vars/{{ project_name }}_vars.yml

  tasks:

      # vars for pg_account.yml task comes from vars/catchpy_vars.yml
      - include_tasks: roles/external/nmaekawa.postgres/tasks/pg_account.yml


