---

- hosts: '{{ target_hosts | default("all", true) }}'
  remote_user: "vagrant"
  become: yes
  become_user: root
  vars_files:
    - vars/common_vars.yml
    - vars/hxat_vars.yml


  tasks:
    - debug:
        var: service_environment['ADMIN_ROLES']

    - name: print python3 version
      shell: /usr/bin/python3 --version | awk '{print $2}'
      register: python_version_output

    - debug:
        var: python_version_output

    - set_fact: python_version={{ python_version_output.stdout }}

    - debug:
        var: python_version

    - debug:
        msg: 'IS python 3.10 -----'
      when: python_version is match('3.10*')

    - debug:
        msg: 'NOT python 3.10 -----'
      when: python_version is not match('3.10*')
