---
    - name: set local image storage, if vagrant
      set_fact:
          loris_image_path: '/vagrant/images'
      when: ec2_tag_cluster == 'vagrant'


    - name: set loris_instance_private_dns - for nginx proxy
      set_fact:
          loris_instance_private_dns: "{{ hostvars[ groups['tag_loris'][0] ]['ec2_private_dns_name'] }}"
      when: loris_instance_private_dns is not defined


    - name: set ids_instance_private_dns - for nginx proxy
      set_fact:
          ids_instance_private_dns: "{{ hostvars[ groups['tag_ids'][0] ]['ec2_private_dns_name'] }}"
      when: ec2_tag_cluster == 'vagrant' and ids_instance_private_dns is not defined

