---
    - name: copy deploy key
      copy:
        src: '{{ service_git_deploy_key_file | mandatory }}'
        dest: '/home/{{ service_user }}/.ssh/id_rsa_{{ service_name }}'
        owner: '{{ service_user }}'
        group: '{{ service_group }}'
        mode: 0600
      when: service_git_deploy_key_file is defined and service_git_deploy_key_file != ''

    - name: git | clone repository with deploy key
      become: yes
      become_user: '{{ service_user }}'
      git:
          repo: '{{ service_git_repo }}'
          accept_hostkey: yes
          update: yes
          clone: yes
          force: yes
          version: '{{ service_git_revision }}'
          dest: '{{ service_install_dir }}'
          key_file: '/home/{{ service_user }}/.ssh/id_rsa_{{ service_name }}'
      when: service_git_deploy_key_file is defined and service_git_deploy_key_file != ''

    - name: git | clone repository
      become: yes
      become_user: '{{ service_user }}'
      git:
          repo: '{{ service_git_repo }}'
          accept_hostkey: yes
          update: yes
          clone: yes
          force: yes
          version: '{{ service_git_revision }}'
          dest: '{{ service_install_dir }}'
      when: not service_git_deploy_key_file is defined or service_git_deploy_key_file == ''

