---

    - name: transfer local manifests
      copy:
          src: '{{ local_manifests_path_tar_gz }}'
          dest: '{{ service_data_dir }}'
          owner: '{{ service_user }}'
          group: '{{ service_group }}'

    - name: unarchive local manifests tar.gz
      unarchive:
          src: '{{ service_data_dir }}/{{ local_manifests_path_tar_gz | basename }}'
          dest: '{{ service_data_dir }}'
          owner: '{{ service_user }}'
          group: '{{ service_group }}'
          remote_src: yes

