---
# beware that the correct dotenv path must be configured in the environment
# prior to calling this play!

    - name: django_manage | apply migrations
      become_user: '{{ service_user }}'
      environment:
          HXMIRADOR_DOTENV_PATH: '{{ service_dotenv_path }}'
          CATCHPY_DOTENV_PATH: '{{ service_dotenv_path }}'
          HXAT_DOTENV_PATH: '{{ service_dotenv_path }}'

      django_manage:
          command: migrate
          app_path: '{{ service_install_dir }}'
          virtualenv: '{{ service_venv_dir }}'


    - name: django_manage | run collectstatic
      become_user: '{{ service_user }}'
      environment:
      # next time, define a standard env var!
          HXMIRADOR_DOTENV_PATH: '{{ service_dotenv_path }}'
          CATCHPY_DOTENV_PATH: '{{ service_dotenv_path }}'
          HXAT_DOTENV_PATH: '{{ service_dotenv_path }}'

      django_manage:
          command: collectstatic
          app_path: '{{ service_install_dir }}'
          virtualenv: '{{ service_venv_dir }}'
      notify: restart webapp
