---
      - name: dotenv | add dotenv_dir to .bashrc
        become_user: "{{ service_user }}"
        lineinfile:
          path: /home/{{ service_user }}/.bashrc
          line: "export {{ service_name | upper }}_DOTENV_PATH={{ service_dotenv_path }}"
          backup: yes
          state: present

      - name: dotenv | drop .env file
        template:
          src: service_dotenv.j2
          dest: "{{ service_dotenv_path }}"
          owner: "{{ service_user }}"
          group: "{{ service_group }}"
          mode: 0640
          backup: yes

      - name: dotenv | drop hxat lti_dict file
        copy:
          src: "{{ lti_dict_local_filepath }}"
          dest: "{{ lti_dict_remote_filepath }}"
          owner: "{{ service_user }}"
          group: "{{ service_group }}"
          mode: 0640
          backup: yes
        when: service_name == "hxat"

