---
# tasks file for webapp_install

      - include_tasks: create_dirs.yml
      - include_tasks: clone_repo.yml
      - include_tasks: venv.yml
      - include_tasks: dotenv.yml
      - include_tasks: gunicorn.yml
      - include_tasks: supervisor.yml

        # could not figure how to restart multiprocess under supervisor
      - name: restart service
        shell: supervisorctl restart '{{ service_name }}:*'
        when: service_daphne is defined

      - name: restart service
        shell: supervisorctl restart '{{ service_name }}'
        when: service_daphne is not defined


