---
# tasks file for webapp_install

      - include_tasks: create_dirs.yml
      - include_tasks: clone_repo.yml
      - include_tasks: venv.yml
      - include_tasks: dotenv.yml
      - include_tasks: gunicorn.yml
      - include_tasks: supervisor.yml

      - name: restart service
        supervisorctl:
            name: "{{ service_name }}"
            state: restarted


