---

    - name: supervisor | ensure supervisor is running
      service:
        name: supervisor
        state: started
        enabled: yes

    - name: supervisor | create supervisor config
      template:
        src: "{{ '../templates/supervisor_asgi_config.j2' if websockets is defined and websockets.service_daphne is defined else '../templates/supervisor_wsgi_config.j2' }}"
        dest: /etc/supervisor/conf.d/{{ service_name }}.conf
        backup: yes

    - name: supervisor | create sock dir, if daphne asgi service
      file:
        path: "{{ websockets.service_daphne.socket_dir }}"
        owner: "{{ service_user }}"
        group: "{{ service_group }}"
        mode: 0755
        state: directory
      when: websockets is defined and websockets.service_daphne is defined

    - name: supervisor | restart supervisor
      service:
        name: supervisor
        state: restarted
        enabled: yes



