---

    - name: supervisor | ensure supervisor is running
      service:
        name: supervisor
        state: started
        enabled: yes

    - name: supervisor | create supervisor config
      template:
        src: "{{ 'supervisor_asgi_config.j2' if service_daphne is defined else 'supervisor_wsgi_config.j2' }}"
        dest: /etc/supervisor/conf.d/{{ service_name }}.conf
        backup: yes

    - name: supervisor | create sock dir, if daphne asgi service
      file:
        path: "{{ service_daphne.socket_dir }}"
        owner: "{{ service_user }}"
        group: "{{ service_group }}"
        mode: 0755
        state: directory
      when: service_daphne is defined

    # could not figure how to restart multiprocess using ansible supervisor module
    - name: restart service
      shell: supervisorctl restart '{{ service_name }}:*'
      when: service_daphne is defined

    - name: restart service
      shell: supervisorctl restart '{{ service_name }}'
      when: service_daphne is not defined


