---
      - name: venv | create service venv
        include_role:
            name: external/nmaekawa.virtualenv
        vars:
            venv_path: "{{ service_venv_dir }}"
            venv_user: "{{ service_user }}"
            venv_group: "{{ service_group }}"
            venv_python_version: 3

      - name: venv | pip install requirements
        become_user: "{{ service_user }}"
        pip:
            chdir: "{{ service_install_dir }}"
            virtualenv: "{{ service_venv_dir }}"
            requirements: "{{ service_install_dir }}/requirements.txt"
            state: present

      - name: venv | pip install service
        become_user: "{{ service_user }}"
        pip:
            chdir: "{{ service_install_dir }}"
            virtualenv: "{{ service_venv_dir }}"
            name: '.'
            editable: yes
            #state: forcereinstall  # assumes setup.py does not list any dependencies!
            # note: i've added the forcereinstall when testing provisioning and
            # changes in the repo, thus forcing reinstall every time would make
            # sure fresh changes to repo wwould be installed.
            # BUT if you want to go back a version, this will run setup.py from
            # the main service (say, catchpy) and sometimes setup.py DOES list
            # dependencies without specific versions... that clobbers the
            # previous install via requirements.txt.


