---
galaxy_info:
  author: nmaekawa
  description: script to copy files to s3
  license: MIT
  min_ansible_version: 2.5
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  galaxy_tags:
  - system
  - ubuntu
  - debian
dependencies: []

