---
  - name: dirs | ensure SUBPROC dirs are present
    file:
      path: "{{ item }}"
      owner: "{{ service_user }}"
      group: "{{ service_group }}"
      mode: 0755
      state: directory
    with_items: "{{ subproc_dirs_to_create }}"

  - name: clone repo | ensure .ssh is present
    file:
      path: "/home/{{ service_user }}/.ssh"
      owner: "{{ service_user }}"
      group: "{{ service_group }}"
      mode: 0700
      state: directory

  - name: clone repo | copy deploy key
    copy:
      src: '{{ subproc_git_deploy_key_file | mandatory }}'
      dest: '/home/{{ service_user }}/.ssh/id_rsa_{{ subproc_name }}'
      owner: '{{ service_user }}'
      group: '{{ service_group }}'
      mode: 0600
    when: subproc_git_deploy_key_file is defined and subproc_git_deploy_key_file != ''

  - name: clone repo | clone repository with deploy key
    become: yes
    become_user: '{{ service_user }}'
    git:
      repo: 'git+{{ subproc_git_repo }}@{{ subproc_git_revision }}'
      accept_hostkey: yes
      update: yes
      clone: yes
      force: yes
      version: '{{ subproc_git_revision }}'
      dest: '{{ subproc_rootdir_base }}/{{ subproc_name }}/{{ subproc_name }}'
      key_file: '/home/{{ service_user }}/.ssh/id_rsa_{{ subproc_name }}'
    when: subproc_git_deploy_key_file is defined and subproc_git_deploy_key_file != ''

  - name: clone repo | clone repository
    become: yes
    become_user: '{{ service_user }}'
    git:
      repo: '{{ subproc_git_repo }}'
      accept_hostkey: yes
      update: yes
      clone: yes
      force: yes
      version: '{{ subproc_git_revision }}'
      dest: '{{ subproc_rootdir_base }}/{{ subproc_name }}/{{ subproc_name }}'
    when: not subproc_git_deploy_key_file is defined or subproc_git_deploy_key_file == ''


  - name: venv | create subproc venv
    include_role:
      name: external/nmaekawa.virtualenv
    vars:
      venv_path: "{{ subproc_venv_dir }}"
      venv_user: "{{ service_user }}"
      venv_group: "{{ service_group }}"
      venv_python_version: 3

  - name: venv | pip install requirements
    become_user: "{{ service_user }}"
    pip:
      chdir: "{{ subproc_rootdir_base }}/{{ subproc_name }}/{{ subproc_name }}"
      virtualenv: "{{ subproc_venv_dir }}"
      requirements: "{{ subproc_rootdir_base }}/{{ subproc_name }}/{{ subproc_name }}/requirements.txt"
      state: present

  - name: venv | pip install service
    become_user: "{{ service_user }}"
    pip:
      chdir: "{{ subproc_rootdir_base }}/{{ subproc_name }}/{{ subproc_name }}"
      virtualenv: "{{ subproc_venv_dir }}"
      name: '.'
      editable: yes


  - name: wrapper | drop subprocess wrapper shell file
    become_user: "{{ service_user }}"
    template:
      src: "{{ subproc_wrapper_template }}"
      dest: "{{ subproc_wrapper_path }}"
      owner: "{{ service_user }}"
      group: "{{ service_group }}"
      mode: 0744
      backup: yes



