---
  - name: dirs | ensure SUBPROC dirs are present
    file:
      path: "{{ item }}"
      owner: "{{ service_user }}"
      group: "{{ service_group }}"
      mode: 0755
      state: directory
    with_items: "{{ subproc_dirs_to_create }}"


  - name: venv | create subproc venv
    include_role:
      name: external/nmaekawa.virtualenv
    vars:
      venv_path: "{{ subproc_venv_dir }}"
      venv_user: "{{ service_user }}"
      venv_group: "{{ service_group }}"
      venv_python_version: 3


  - name: venv | pip install SUBPROC from repo
    become_user: "{{ service_user }}"
    pip:
      virtualenv: "{{ subproc_venv_dir }}"
      name: 'git+{{ subproc_git_repo }}@{{ subproc_git_revision }}'
      state: present


  - name: wrapper | drop subprocess wrapper shell file
    become_user: "{{ service_user }}"
    template:
      src: wrapper.sh.j2
      dest: "{{ service_wrapper_path }}"
      owner: "{{ service_user }}"
      group: "{{ service_group }}"
      mode: 0744
      backup: yes



