---
    - include_tasks: create_dirs.yml

    - name: clone repo
      become_user: '{{ app_user }}'
      git:
          repo: '{{ loris_git_repo }}'
          update: yes
          clone: yes
          force: yes
          version: '{{ loris_git_version }}'
          dest: '{{ app_source_path }}'

    - name: drop hx-custom setup.py
      copy:
          src: files/setup.py
          backup: yes
          dest: '{{ app_source_path }}'
          owner: '{{ loris_user }}'
          group: '{{ loris_group }}'

    - include_tasks: pip_requirements.yml

    - name: drop loris config
      template:
          src: templates/loris2.conf.j2
          dest: '{{ loris_config_path }}/{{ loris_config_filename }}'
          owner: '{{ loris_user }}'
          group: '{{ loris_group }}'
