---

    - name: ensure aws creds dir exists
      file:
          path: /home/{{ service_user }}/.aws
          owner: '{{ service_user }}'
          group: '{{ service_group }}'
          mode: 0750
          state: directory

    - name: add AWS CREDENTIALS!
      copy:
          src: ~/.aws/loris-credentials
          dest: /home/{{ service_user }}/.aws/credentials
          owner: '{{ service_user }}'
          group: '{{ service_group }}'
          mode: 0600


