---

    - name: clone repository
      become_user: '{{ service_user }}'
      git:
          repo: '{{ loris_git_repo }}'
          update: yes
          clone: yes
          force: yes
          version: '{{ loris_git_version }}'
          dest: '{{ service_install_dir }}'

    - name: drop simpler setup.py
      become_user: '{{ service_user }}'
      copy:
          src: ../files/setup.py
          dest: '{{ service_install_dir }}/setup.py'
          mode: 0644
          backup: yes

    - name: drop wsgi.py
      become_user: '{{ service_user }}'
      template:
          src: ../templates/wsgi.py.j2
          dest: '{{ service_install_dir }}/loris/wsgi.py'
          mode: 0644
          backup: yes

    - name: drop static content
      become_user: '{{ service_user }}'
      copy:
          src: ../files/loris-static/
          dest: '{{ service_static_dir }}/'
          owner: '{{ service_user }}'
          group: '{{ service_group }}'

    - name: overwrite loris icon with hx
      become_user: '{{ service_user }}'
      copy:
          src: ../files/loris-static/icons/
          dest: '{{ service_static_dir }}/icons'
          owner: '{{ service_user }}'
          group: '{{ service_group }}'

    - name: pip install loris from source
      become_user: '{{ service_user }}'
      pip:
          name: '.'
          chdir: '{{ service_install_dir }}'
          editable: '{{ ec2_tag_cluster == "vagrant" }}'
          virtualenv: "{{ service_venv_dir }}"
          state: forcereinstall
