---
    - name: upgrade pip
      command: "pip install --upgrade pip"

    - name: install python dependencies
      pip:
          name: "{{ item.name }}"
          version: "{{ item.version }}"
      with_items: "{{ loris_python_dependencies }}"

