---

    - name: gunicorn | install gunicorn
      become_user: '{{ service_user }}'
      pip:
        name: gunicorn
        virtualenv: '{{ service_venv_dir }}'
        state: present

    - name: gunicorn | create gunicorn config
      template:
        src: ../templates/gunicorn_start.j2
        dest: "{{ service_bin_dir }}/gunicorn_start"
        owner: "{{ service_user }}"
        group: "{{ service_group }}"
        mode: 0755
        backup: yes

    - name: supervisor | ensure supervisor is running
      service:
        name: supervisor
        state: started
        enabled: yes

    - name: supervisor | create supervisor config
      template:
        src: ../templates/supervisor_config.j2
        dest: /etc/supervisor/conf.d/{{ service_name }}.conf
        backup: yes

    - name: supervisor | reload supervisor config for {{ service_name }}
      supervisorctl:
        name: "{{ service_name }}"
        state: present

