---
    - name: venv | create service venv
      include_role:
          name: external/nmaekawa.virtualenv
      vars:
          venv_path: "{{ service_venv_dir }}"
          venv_user: "{{ service_user }}"
          venv_group: "{{ service_group }}"
          venv_python_version: 3


