---
#- import_playbook: common_play.yml

- hosts: '{{ target_hosts | default("tag_service_inspector", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  vars:
    postgres_version: 13
  vars_files:
      - vars/common_vars.yml
  handlers:
    - include_tasks: handlers/main.yml

  tasks:
    - include_role:
        name: external/nmaekawa.apt
      vars:
        apt_other_packages:
          - 'build-essential'
          - 'libffi-dev'
          - 'openssl'
          - 'libcurl4-openssl-dev'
          - 'unzip'
          - 'python3-pip'
          - 'python3-dev'
          - 'python3-setuptools'
          - 'libpq-dev'
          - 'postgresql-client'
          - 'nginx'
          - 'supervisor'
          - 'postgresql-client'

    - name: install redis
      include_role:
        name: external/geerlingguy.redis

    - name: install pg client
      include_tasks: roles/external/nmaekawa.postgres/tasks/pg_install_client.yml


- hosts: '{{ target_hosts | default("tag_service_inspector", true) }}'
  remote_user: "{{ my_remote_user }}"
  become: yes
  vars_files:
    - vars/common_vars.yml
    - vars/inspector_vars.yml
  handlers:
    - include_tasks: handlers/main.yml
    - include_tasks: roles/webapp_install/handlers/main.yml

  tasks:
    - name: install webapp
      include_role:
        name: webapp_install

    - name: run migration and collectstatic
      include_tasks: roles/webapp_install/tasks/django_manage.yml

    - name: config nginx
      include_role:
        name: nginx


